# -*- coding: utf-8 -*-
"""project code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFsunwLG7NlWYkqrjymTdERj6u10F9SR

#Stage 1:
"""

import tensorflow as tf
print("TensorFlow Version:", tf.__version__)
print("GPU Available:", tf.config.list_physical_devices('GPU'))

from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy('mixed_float16')
print("Mixed Precision:", mixed_precision.global_policy().name)

"""# Stage 2: Libraries Import"""

import os
import cv2                    # Image processing
import numpy as np            # Arrays
import matplotlib.pyplot as plt  # Graphs
import seaborn as sns         # Pretty confusion matrix
import kagglehub              # Download dataset from Kaggle
import json                   # Save metadata

from pathlib import Path
from tensorflow.keras.preprocessing.image import (
    ImageDataGenerator,
    load_img,
    img_to_array
)
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)
from sklearn.metrics import classification_report, confusion_matrix

print("All imports successful")

"""# Stage 3: Configuration - Numbers fix panna"""

IMG_SIZE    = (128, 128)  # MobileNetV2-ku 128 enough
BATCH_SIZE  = 32          # 64 vechirundhen - memory error! 32 safe
EPOCHS      = 30          # Too much la? Early stopping irukku, okay
STEPS_TRAIN = 100         # Colab timeout aagaama
STEPS_VALID = 25

# ViT settings
PATCH_SIZE  = 8           # 128/8 = 16x16 = 256 patches
NUM_HEADS   = 2           # Simple-a vachom
VIT_BLOCKS  = 2           # 2 transformer blocks enough
EMBED_DIM   = 64          # Token size

"""# Stage 4: Dataset Download"""

path = kagglehub.dataset_download("ashishmotwani/tomato")
path = Path(path)

TRAIN_DIR = path / "train"
VALID_DIR = path / "valid"

print("Train Folder Exists:", TRAIN_DIR.exists())
print("Validation Folder Exists:", VALID_DIR.exists())

# Enna classes irukku nu paakalam
print("\nClasses:")
for cls in sorted(os.listdir(TRAIN_DIR)):
    print(f"  - {cls}")

"""#Stage 5: Severity Map"""

# Biology paper padichen - ithuvara values fix panninen
SEVERITY_MAP = {
    "Tomato_healthy":                              0.00,  # No disease
    "Tomato_Early_blight":                         0.40,  # Moderate
    "Tomato_Spider_mites Two-spotted_spider_mite": 0.35,  # Low-moderate
    "Tomato__Target_Spot":                         0.45,  # Moderate
    "Tomato_Bacterial_spot":                       0.50,  # Moderate-high
    "Tomato_Septoria_leaf_spot":                   0.45,  # Moderate
    "Tomato_Leaf_Mold":                            0.55,  # Moderate-high
    "Tomato__Tomato_mosaic_virus":                 0.60,  # High
    "Tomato__Tomato_YellowLeaf__Curl_Virus":       0.70,  # High
    "Tomato_Late_blight":                          0.85,  # Very high!
}

"""#Stage 6: Data Generators"""

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Training - augmentation + normalization
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,  # [-1, 1] range!

    # Augmentation - real world variations simulate pannurom
    rotation_range=30,        # Leaf different angle-la irukum
    zoom_range=0.25,          # Camera far/close
    width_shift_range=0.2,    # Leaf not always centered
    height_shift_range=0.2,
    horizontal_flip=True,     # Left-right flip okay
    brightness_range=[0.8, 1.2],  # Sunlight vary aagum
    fill_mode='nearest'       # Empty pixels fill panna
)

# Validation - only normalization, NO augmentation!
valid_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

# Flow from directory
train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,      # Resize to 128x128
    batch_size=BATCH_SIZE,     # 32 images at a time
    class_mode='categorical',  # One-hot encoding
    shuffle=True               # Random order
)

valid_generator = valid_datagen.flow_from_directory(
    VALID_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False              # Validation - order matter!
)

# Class names and count
class_names = list(train_generator.class_indices.keys())
NUM_CLASSES = train_generator.num_classes

# Each class-ku severity map panna
class_index_to_severity = {
    idx: SEVERITY_MAP.get(cls, 0.3)
    for cls, idx in train_generator.class_indices.items()
}

print(f"Number of Classes: {NUM_CLASSES}")

"""#Stage 7: Sample Images Check"""

images, labels = next(train_generator)

# MobileNetV2 preprocessing undone panna (display-ku matum)
display_images = (images + 1.0) / 2.0  # [-1,1] → [0,1]
display_images = np.clip(display_images, 0, 1)

plt.figure(figsize=(14, 6))
for i in range(6):
    plt.subplot(2, 3, i + 1)
    plt.imshow(display_images[i])
    cls_idx  = np.argmax(labels[i])
    severity = class_index_to_severity[cls_idx]
    plt.title(
        f"{class_names[cls_idx]}\nSev: {severity:.2f}",
        fontsize=7
    )
    plt.axis("off")
plt.tight_layout()
plt.show()

"""# Stage 8: CNN Branch - MobileNetV2"""

cnn_input = layers.Input(shape=(*IMG_SIZE, 3), name="cnn_input")

# ImageNet pretrained - 1.4M images already learned!
mobilenet = MobileNetV2(
    input_shape=(*IMG_SIZE, 3),
    include_top=False,    # Remove final classifier layer
    weights="imagenet"    # Use pretrained weights!
)

# Phase 1: Freeze - don't change ImageNet knowledge yet
mobilenet.trainable = False

# Feature map extract
cnn_features_map = mobilenet(cnn_input, training=False)
# Output shape: (4, 4, 1280)
# 4x4 spatial positions, 1280 feature channels

# Reshape: 4x4 = 16 spatial tokens
n_spatial  = 4 * 4  # = 16
cnn_tokens = layers.Reshape(
    (n_spatial, 1280),
    name="cnn_tokens"
)(cnn_features_map)
# Now: (16, 1280)

# Project 1280 → 64 (match ViT dimension!)
cnn_projected = layers.Dense(
    EMBED_DIM,           # 64
    activation="relu",
    name="cnn_projection"
)(cnn_tokens)
# Final: (16, 64) ✅

cnn_branch = models.Model(
    cnn_input,
    cnn_projected,
    name="CNN_MobileNetV2_Branch"
)
print(f"CNN Branch output: {cnn_branch.output_shape}")
# (None, 16, 64)

"""#Stage 9: ViT Branch

"""

VIT_PATCHES = (IMG_SIZE[0] // PATCH_SIZE) ** 2
# = (128 // 8)² = 16² = 256 patches

vit_input = layers.Input(shape=(*IMG_SIZE, 3), name="vit_input")

# Step 1: Patch Embedding
# Conv2D with stride=patch_size creates patches automatically!
x = layers.Conv2D(
    filters=EMBED_DIM,   # 64
    kernel_size=PATCH_SIZE,  # 8x8 patches
    strides=PATCH_SIZE,      # Non-overlapping
    padding="valid",
    name="patch_embedding"
)(vit_input)
# Output: (16, 16, 64)

# Step 2: Reshape to sequence
x = layers.Reshape(
    (VIT_PATCHES, EMBED_DIM),  # (256, 64)
    name="patch_sequence"
)(x)

# Step 3: Positional Encoding
# ViT-ku position sense illai by default!
positions    = tf.range(start=0, limit=VIT_PATCHES, delta=1)
pos_encoding = layers.Embedding(
    input_dim=VIT_PATCHES,   # 256 positions
    output_dim=EMBED_DIM     # 64 dim each
)(positions)
x = x + pos_encoding  # Add position info to patches

# Step 4: Transformer Blocks (x2)
for i in range(VIT_BLOCKS):  # 2 blocks

    # Self-Attention: Every patch attends to every other patch
    attn = layers.MultiHeadAttention(
        num_heads=NUM_HEADS,                    # 2 heads
        key_dim=EMBED_DIM // NUM_HEADS,         # 32 per head
        name=f"self_attn_{i}"
    )(x, x)  # Query=x, Key=x, Value=x (self attention!)

    # Residual connection
    x = layers.Add()([x, attn])
    x = layers.LayerNormalization()(x)

    # Feed Forward Network
    ffn = layers.Dense(EMBED_DIM * 2, activation="relu")(x)  # 128
    ffn = layers.Dense(EMBED_DIM)(ffn)  # back to 64
    x = layers.Add()([x, ffn])
    x = layers.LayerNormalization()(x)

vit_branch = models.Model(vit_input, x, name="ViT_Branch")
print(f"ViT Branch output: {vit_branch.output_shape}")
# (None, 256, 64)

"""#Stage 10: Cross-Attention Fusion"""

hybrid_input = layers.Input(shape=(*IMG_SIZE, 3), name="hybrid_input")

# Same image, two different branches
cnn_features = cnn_branch(hybrid_input)  # (16, 64)  - local
vit_features = vit_branch(hybrid_input)  # (256, 64) - global

# Cross-Attention!
# CNN asks questions (Query)
# ViT provides answers (Key, Value)
cross_attn = layers.MultiHeadAttention(
    num_heads=NUM_HEADS,
    key_dim=EMBED_DIM // NUM_HEADS,
    name="cross_attention"
)(
    query=cnn_features,   # CNN: "what's important here?"
    key=vit_features,     # ViT: "here's the global context"
    value=vit_features    # ViT: "here's the information"
)

# Residual + Norm
fusion = layers.Add(name="cross_residual")([cnn_features, cross_attn])
fusion = layers.LayerNormalization(name="cross_norm")(fusion)

# Pool and Dense
fusion_pooled = layers.GlobalAveragePooling1D(
    name="fusion_pool"
)(fusion)
# (16, 64) → (64,)

fusion_output = layers.Dense(
    256, activation="relu", name="fusion_dense"
)(fusion_pooled)
# (256,)

fusion_output = layers.Dropout(0.4)(fusion_output)
# Dropout - prevent overfitting

"""#Stage 11: Output Heads

"""

# Head 1: Disease Classification
disease_output = layers.Dense(
    NUM_CLASSES,          # 11 classes
    activation="softmax", # Probabilities sum to 1
    dtype="float32",      # Mixed precision override
    name="disease_output"
)(fusion_output)
# Output: [0.02, 0.85, 0.01, ...] → argmax → "Late Blight"

# Head 2: Severity Estimation
sev = layers.Dense(64, activation="relu")(fusion_output)
severity_output = layers.Dense(
    1,
    activation="sigmoid", # 0 to 1 range
    dtype="float32",
    name="severity_output"
)(sev)
# Output: 0.85 → "85% severe!"

# Final Model
hybrid_model = models.Model(
    inputs=hybrid_input,
    outputs=[disease_output, severity_output],
    name="Hybrid_MobileNetV2_ViT"
)

hybrid_model.summary()

"""#Stage 12: Custom Generator"""

def multi_output_generator(generator, class_to_severity):
    while True:
        images, labels = next(generator)

        # Class index from one-hot labels
        class_indices = np.argmax(labels, axis=1)

        # Map each class → severity score
        severity_labels = np.array(
            [class_to_severity[idx] for idx in class_indices],
            dtype=np.float32
        ).reshape(-1, 1)
        # Shape: (32, 1)

        yield images, {
            "disease_output": labels,         # One-hot
            "severity_output": severity_labels # Severity score
        }

train_multi_gen = multi_output_generator(
    train_generator,
    class_index_to_severity
)
valid_multi_gen = multi_output_generator(
    valid_generator,
    class_index_to_severity
)

"""#Stage 13: Phase 1 Training"""

def get_callbacks(phase):
    return [
        # Stop if no improvement
        EarlyStopping(
            monitor="val_disease_output_accuracy",
            mode="max",
            patience=4,          # 4 epochs wait
            restore_best_weights=True
        ),
        # Reduce LR if loss stuck
        ReduceLROnPlateau(
            monitor="val_loss",
            mode="min",
            factor=0.5,          # LR halve pannu
            patience=2,
            min_lr=1e-7
        ),
        # Save best model
        ModelCheckpoint(
            f"best_model_phase{phase}.keras",
            monitor="val_disease_output_accuracy",
            mode="max",
            save_best_only=True
        )
    ]

# Compile
hybrid_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss={
        "disease_output": "categorical_crossentropy",
        "severity_output": "mse"
    },
    loss_weights={
        "disease_output": 1.0,  # Main task
        "severity_output": 0.5  # Supporting task
    },
    metrics={
        "disease_output": ["accuracy"],
        "severity_output": ["mae"]
    }
)

# Train Phase 1
history1 = hybrid_model.fit(
    train_multi_gen,
    validation_data=valid_multi_gen,
    steps_per_epoch=STEPS_TRAIN,   # 100 steps
    validation_steps=STEPS_VALID,  # 25 steps
    epochs=10,
    callbacks=get_callbacks(1),
    verbose=1
)

"""#Stage 14: Phase 2 Fine-tuning"""

# Unfreeze MobileNetV2
mobilenet.trainable = True

# But freeze early layers (basic features ruin aagadha)
for layer in mobilenet.layers[:-30]:
    layer.trainable = False

trainable_count = sum(1 for l in mobilenet.layers if l.trainable)
print(f"Unfrozen layers: {trainable_count}/{len(mobilenet.layers)}")

# Recompile with LOWER learning rate!
hybrid_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    # 10x lower than Phase 1!
    loss={
        "disease_output": "categorical_crossentropy",
        "severity_output": "mse"
    },
    loss_weights={
        "disease_output": 1.0,
        "severity_output": 0.5
    },
    metrics={
        "disease_output": ["accuracy"],
        "severity_output": ["mae"]
    }
)

history2 = hybrid_model.fit(
    train_multi_gen,
    validation_data=valid_multi_gen,
    steps_per_epoch=STEPS_TRAIN,
    validation_steps=STEPS_VALID,
    epochs=15,
    callbacks=get_callbacks(2),
    verbose=1
)

"""#Stage 15: Training Curves Plot"""

def merge_history(h1, h2, key):
    return h1.history.get(key, []) + h2.history.get(key, [])

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Accuracy plot
axes[0].plot(
    merge_history(history1, history2, "disease_output_accuracy"),
    label="Train"
)
axes[0].plot(
    merge_history(history1, history2, "val_disease_output_accuracy"),
    label="Val"
)
# Red line = where Phase 2 starts
axes[0].axvline(
    x=len(history1.history["loss"]),
    color="red",
    linestyle="--",
    label="Fine-tune start"
)
axes[0].set_title("Accuracy")
axes[0].legend()

# Loss plot
axes[1].plot(merge_history(history1, history2, "loss"), label="Train")
axes[1].plot(merge_history(history1, history2, "val_loss"), label="Val")
axes[1].axvline(x=len(history1.history["loss"]), color="red", linestyle="--")
axes[1].set_title("Loss")
axes[1].legend()

# Severity MAE
axes[2].plot(
    merge_history(history1, history2, "severity_output_mae"),
    label="Train"
)
axes[2].plot(
    merge_history(history1, history2, "val_severity_output_mae"),
    label="Val"
)
axes[2].set_title("Severity MAE")
axes[2].legend()

plt.tight_layout()
plt.savefig("training_curves.png", dpi=150)
plt.show()

"""#Stage 16: Evaluation"""

y_true, y_pred = [], []
y_sev_pred, y_sev_true = [], []

for i in range(len(valid_generator)):
    imgs, labels = valid_generator[i]
    preds = hybrid_model.predict(imgs, verbose=0)

    idxs = np.argmax(labels, axis=1)
    y_true.extend(idxs)
    y_pred.extend(np.argmax(preds[0], axis=1))
    y_sev_pred.extend(preds[1].flatten())
    y_sev_true.extend([class_index_to_severity[idx] for idx in idxs])

# Classification report
print(classification_report(
    y_true, y_pred,
    target_names=class_names
))

# Severity MAE
mae = np.mean(np.abs(
    np.array(y_sev_true) - np.array(y_sev_pred)
))
print(f"Severity MAE: {mae:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(12, 9))
sns.heatmap(cm, annot=True, fmt="d", cmap="YlOrRd",
            xticklabels=class_names,
            yticklabels=class_names)
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

"""#Stage 17: Live Prediction"""

from google.colab import files
uploaded = files.upload()  # Your phone photo!

for filename in uploaded.keys():
    image_path = Path(filename)

    # Preprocess
    img = load_img(image_path, target_size=IMG_SIZE)
    img_array = preprocess_input(
        np.expand_dims(img_to_array(img), axis=0)
    )
    # Shape: (1, 128, 128, 3)

    # Predict
    preds      = hybrid_model.predict(img_array)
    pred_idx   = np.argmax(preds[0], axis=1)[0]
    confidence = np.max(preds[0])
    severity   = preds[1][0][0] * 100  # 0-1 → 0-100%

    print(f"Disease  : {class_names[pred_idx]}")
    print(f"Confidence: {confidence:.2%}")
    print(f"Severity  : {severity:.2f}%")

    # Show image
    plt.imshow(load_img(image_path))
    plt.title(
        f"{class_names[pred_idx]}\n"
        f"Conf: {confidence:.2%} | Sev: {severity:.2f}%"
    )
    plt.axis("off")
    plt.show()

"""# Stage 18: Grad-CAM"""

# Find last Conv2D in MobileNetV2
all_conv_layers = [
    l for l in mobilenet.layers
    if isinstance(l, tf.keras.layers.Conv2D)
]
last_conv_layer = all_conv_layers[-1]

# Grad-CAM model
grad_model = tf.keras.models.Model(
    inputs=mobilenet.input,
    outputs=[last_conv_layer.output, mobilenet.output]
)

def make_gradcam_heatmap(img_array):
    with tf.GradientTape() as tape:
        conv_out, preds = grad_model(img_array, training=False)
        class_ch = tf.reduce_max(preds, axis=-1)

    # Gradients
    grads  = tape.gradient(class_ch, conv_out)
    pooled = tf.reduce_mean(grads, axis=(0, 1, 2))

    # Weighted sum
    heatmap = tf.reduce_sum(conv_out[0] * pooled, axis=-1)
    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()

# Generate heatmap
original = img_to_array(
    load_img(image_path, target_size=IMG_SIZE)
).astype("uint8")

heatmap   = make_gradcam_heatmap(img_array)
heatmap   = np.squeeze(heatmap).astype("float32")
W, H      = IMG_SIZE[1], IMG_SIZE[0]
heatmap_r = np.uint8(255 * cv2.resize(heatmap, (W, H)))
heatmap_c = cv2.cvtColor(
    cv2.applyColorMap(heatmap_r, cv2.COLORMAP_JET),
    cv2.COLOR_BGR2RGB
)

# Overlay
overlay = cv2.addWeighted(original, 0.6, heatmap_c, 0.4, 0)

# Plot
fig, axes = plt.subplots(1, 3, figsize=(13, 4))
for ax, im, title in zip(
    axes,
    [original, heatmap, overlay],
    ["Original", "Grad-CAM", "Overlay"]
):
    ax.imshow(im, cmap="jet" if title=="Grad-CAM" else None)
    ax.set_title(title)
    ax.axis("off")

plt.suptitle(f"{class_names[pred_idx]} | Severity: {severity:.2f}%")
plt.savefig("gradcam.png", dpi=150)
plt.show()

"""#Stage 19: Save Model"""

# Save model
hybrid_model.save("hybrid_tomato_disease_model_final.keras")

# Save class names + severity map
with open("class_metadata.json", "w") as f:
    json.dump({
        "class_names": class_names,
        "severity_map": {
            str(k): float(v)
            for k, v in class_index_to_severity.items()
        }
    }, f, indent=2)

print("Model saved")
print("Metadata saved")
print("All done ")

